/**
 * wasm_ricci.cpp - WebAssembly 入口点，离散 Ricci 流参数化
 *
 * 编译命令:
 *   emcc wasm_ricci.cpp RicciFlow.cpp Mesh.cpp MeshIO.cpp Solver.cpp
 *        Parameterization.cpp QcError.cpp Vertex.cpp Edge.cpp
 *        Face.cpp HalfEdge.cpp
 *        -I./deps -I./deps/Eigen -I.
 *        -s MODULARIZE=1 -s EXPORT_NAME="RicciFlowSolver"
 *        -s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','getValue','setValue']"
 *        -s "EXPORTED_FUNCTIONS=['_malloc','_free','_solve_ricci',
 *                              '_get_ricci_uv_result','_get_ricci_uv_result_size',
 *                              '_get_ricci_last_time_ms','_ricci_dispose']"
 *        -s ALLOW_MEMORY_GROWTH=1 -s WASM=1
 *        -std=c++17 -O2
 *        -o ../assets/wasm/ricci_solver.js
 */

#include <emscripten.h>
#include <vector>
#include <string>
#include <sstream>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <limits>

#include "Mesh.h"
#include "MeshIO.h"
#include "RicciFlow.h"
#include "Parameterization.h"

// ==================== 全局网格实例 ====================
static Mesh* g_mesh = nullptr;
static double g_lastTimeMs = 0.0;
static std::vector<double> g_uv_result;

// ==================== 辅助函数 ====================

static bool loadMeshFromArrays(const double* positions, int posLen,
                                const int* faces, int faceLen)
{
    if (g_mesh) {
        delete g_mesh;
        g_mesh = nullptr;
    }
    
    if (posLen < 9 || faceLen < 3) {
        return false;
    }

    g_mesh = new Mesh();
    
    size_t nVerts = posLen / 3;
    size_t nFaces = faceLen / 3;

    std::stringstream obj_ss;
    obj_ss << "# Generated by RicciFlowSolver WASM\n";
    obj_ss << "# " << nVerts << " vertices, " << nFaces << " faces\n\n";

    for (size_t i = 0; i < nVerts; i++) {
        obj_ss << "v " << positions[i * 3] << " "
               << positions[i * 3 + 1] << " "
               << positions[i * 3 + 2] << "\n";
    }

    obj_ss << "\n";
    for (size_t i = 0; i < nFaces; i++) {
        obj_ss << "f " << faces[i * 3] + 1 << " "
               << faces[i * 3 + 1] + 1 << " "
               << faces[i * 3 + 2] + 1 << "\n";
    }

    std::string obj_str = obj_ss.str();

    const char* tmpPath = "/tmp/input_ricci.obj";
    FILE* fp = fopen(tmpPath, "wb");
    if (!fp) return false;
    fwrite(obj_str.c_str(), 1, obj_str.size(), fp);
    fclose(fp);

    bool ok = g_mesh->read(std::string(tmpPath));
    if (!ok) {
        delete g_mesh;
        g_mesh = nullptr;
        return false;
    }

    return true;
}

// ==================== 导出的 C 函数 ====================

extern "C" {

/**
 * 求解离散 Ricci 流参数化
 * @param posPtr 顶点数据指针 (double 数组)
 * @param posLen 顶点数据长度 (double 个数)
 * @param facePtr 面数据指针 (int 数组)
 * @param faceLen 面数据长度 (int 个数)
 * @param optScheme 优化方法: 0=梯度下降, 1=牛顿法(推荐), 3=LBFGS
 * @return 0 成功, -1 失败
 */
EMSCRIPTEN_KEEPALIVE
int solve_ricci(double* posPtr, int posLen, int* facePtr, int faceLen, int optScheme) {
    if (!posPtr || !facePtr || posLen < 9 || faceLen < 3) {
        return -1;
    }

    if (!loadMeshFromArrays(posPtr, posLen, facePtr, faceLen)) {
        return -1;
    }

    auto t_start = std::chrono::high_resolution_clock::now();

    // Ricci flow: 0=GRAD_DESCENT, 1=NEWTON, 3=LBFGS
    if (optScheme != 0 && optScheme != 1 && optScheme != 3) {
        optScheme = 1; // 默认牛顿法
    }

    RicciFlow ricci(*g_mesh, optScheme);
    ricci.parameterize();

    auto t_end = std::chrono::high_resolution_clock::now();
    g_lastTimeMs = std::chrono::duration<double, std::milli>(t_end - t_start).count();

    // 提取 UV 到全局变量
    g_uv_result.clear();
    g_uv_result.reserve(g_mesh->vertices.size() * 2);

    double min_u = std::numeric_limits<double>::infinity();
    double max_u = -std::numeric_limits<double>::infinity();
    double min_v = std::numeric_limits<double>::infinity();
    double max_v = -std::numeric_limits<double>::infinity();
    
    for (VertexCIter vit = g_mesh->vertices.begin(); vit != g_mesh->vertices.end(); ++vit) {
        double u = vit->uv.x();
        double v = vit->uv.y();
        if (u < min_u) min_u = u;
        if (u > max_u) max_u = u;
        if (v < min_v) min_v = v;
        if (v > max_v) max_v = v;
    }
    
    double range_u = max_u - min_u;
    double range_v = max_v - min_v;
    if (range_u < 1e-10) range_u = 1.0;
    if (range_v < 1e-10) range_v = 1.0;
    
    for (VertexCIter vit = g_mesh->vertices.begin(); vit != g_mesh->vertices.end(); ++vit) {
        g_uv_result.push_back((vit->uv.x() - min_u) / range_u);
        g_uv_result.push_back((vit->uv.y() - min_v) / range_v);
    }

    return 0;
}

/**
 * 获取 UV 结果数组指针
 */
EMSCRIPTEN_KEEPALIVE
double* get_ricci_uv_result() {
    if (g_uv_result.empty()) return nullptr;
    return g_uv_result.data();
}

/**
 * 获取 UV 结果数组长度 (double 个数)
 */
EMSCRIPTEN_KEEPALIVE
int get_ricci_uv_result_size() {
    return static_cast<int>(g_uv_result.size());
}

/**
 * 获取最后一次求解耗时 (ms)
 */
EMSCRIPTEN_KEEPALIVE
double get_ricci_last_time_ms() {
    return g_lastTimeMs;
}

/**
 * 释放全局网格资源
 */
EMSCRIPTEN_KEEPALIVE
void ricci_dispose() {
    if (g_mesh) {
        delete g_mesh;
        g_mesh = nullptr;
    }
    g_uv_result.clear();
    g_uv_result.shrink_to_fit();
}

} // extern "C"
