/**
 * wasm_main.cpp - WebAssembly 入口点
 * 将 conformal-parameterization 编译为 WASM
 *
 * 编译命令:
 *   call "%EMSDK%\emsdk_env.bat"
 *   emcc wasm_main.cpp Mesh.cpp MeshIO.cpp Lscm.cpp ^
 *        Parameterization.cpp QcError.cpp Solver.cpp ^
 *        Utils.cpp Vertex.cpp Edge.cpp Face.cpp HalfEdge.cpp ^
 *        -I./deps -I./deps/Eigen -I. ^
 *        -s MODULARIZE=1 -s EXPORT_NAME="LSCMSolver" ^
 *        -s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','stringToUTF8','lengthBytesUTF8','_malloc','_free']" ^
 *        -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 ^
 *        -std=c++17 -O2 ^
 *        -o ../assets/wasm/lscm_solver.js
 */

#include <emscripten.h>
#include <vector>
#include <string>
#include <sstream>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <cmath>

#include "Mesh.h"
#include "MeshIO.h"
#include "Lscm.h"
#include "Parameterization.h"

// ==================== 全局网格实例 ====================
static Mesh* g_mesh = nullptr;
static double g_lastTimeMs = 0.0;
static std::vector<double> g_uv_result;

// ==================== 辅助函数 ====================

static bool loadMeshFromArrays(const double* positions, int posLen,
                                const int* faces, int faceLen)
{
    if (g_mesh) {
        delete g_mesh;
        g_mesh = nullptr;
    }
    
    if (posLen < 9 || faceLen < 3) {
        return false;
    }

    g_mesh = new Mesh();
    
    size_t nVerts = posLen / 3;
    size_t nFaces = faceLen / 3;

    std::stringstream obj_ss;
    obj_ss << "# Generated by LSCMSolver WASM\n";
    obj_ss << "# " << nVerts << " vertices, " << nFaces << " faces\n\n";

    for (size_t i = 0; i < nVerts; i++) {
        obj_ss << "v " << positions[i * 3] << " "
               << positions[i * 3 + 1] << " "
               << positions[i * 3 + 2] << "\n";
    }

    obj_ss << "\n";
    for (size_t i = 0; i < nFaces; i++) {
        obj_ss << "f " << faces[i * 3] + 1 << " "
               << faces[i * 3 + 1] + 1 << " "
               << faces[i * 3 + 2] + 1 << "\n";
    }

    std::string obj_str = obj_ss.str();

    const char* tmpPath = "/tmp/input.obj";
    FILE* fp = fopen(tmpPath, "wb");
    if (!fp) return false;
    fwrite(obj_str.c_str(), 1, obj_str.size(), fp);
    fclose(fp);

    bool ok = g_mesh->read(std::string(tmpPath));
    if (!ok) {
        delete g_mesh;
        g_mesh = nullptr;
        return false;
    }

    return true;
}

// ==================== 导出的 C 函数 ====================

extern "C" {

/**
 * 求解 LSCM 参数化
 * @param posPtr 顶点数据指针 (double 数组)
 * @param posLen 顶点数据长度 (double 个数)
 * @param facePtr 面数据指针 (int 数组)
 * @param faceLen 面数据长度 (int 个数)
 * @param anchor0 第一个锚点索引
 * @param anchor1 第二个锚点索引
 * @return 0 成功, -1 失败
 */
EMSCRIPTEN_KEEPALIVE
int solve_lscm(double* posPtr, int posLen, int* facePtr, int faceLen, int anchor0, int anchor1) {
    if (!posPtr || !facePtr || posLen < 9 || faceLen < 3) {
        return -1;
    }

    // 加载网格
    if (!loadMeshFromArrays(posPtr, posLen, facePtr, faceLen)) {
        return -1;
    }

    // 计时并开始求解
    auto t_start = std::chrono::high_resolution_clock::now();

    g_mesh->delaunayize();
    double distortion = g_mesh->parameterize(LSCM);

    auto t_end = std::chrono::high_resolution_clock::now();
    g_lastTimeMs = std::chrono::duration<double, std::milli>(t_end - t_start).count();

    // 提取 UV 到全局变量
    g_uv_result.clear();
    g_uv_result.reserve(g_mesh->vertices.size() * 2);
    for (VertexCIter v = g_mesh->vertices.begin(); v != g_mesh->vertices.end(); v++) {
        g_uv_result.push_back(v->uv.x());
        g_uv_result.push_back(v->uv.y());
    }

    return 0;
}

/**
 * 获取 UV 结果数组指针
 * @return 指向 UV 数组的指针 (u0,v0,u1,v1,...)
 */
EMSCRIPTEN_KEEPALIVE
double* get_uv_result() {
    if (g_uv_result.empty()) return nullptr;
    return g_uv_result.data();
}

/**
 * 获取 UV 结果数组长度 (double 个数)
 */
EMSCRIPTEN_KEEPALIVE
int get_uv_result_size() {
    return static_cast<int>(g_uv_result.size());
}

/**
 * 获取最后一次求解耗时 (ms)
 */
EMSCRIPTEN_KEEPALIVE
double get_last_time_ms() {
    return g_lastTimeMs;
}

/**
 * 释放全局网格资源
 */
EMSCRIPTEN_KEEPALIVE
void dispose() {
    if (g_mesh) {
        delete g_mesh;
        g_mesh = nullptr;
    }
    g_uv_result.clear();
    g_uv_result.shrink_to_fit();
}

} // extern "C"
